services:
  backend:
    container_name: pedidofacil_api
    build:
      context: .
      dockerfile: Dockerfile
      target: production
    ports:
      - '3333:3333'
    networks:
      - pedidofacil_default
    restart: unless-stopped
    privileged: true
    env_file: .env.local
    depends_on:
      - db
    command: >
      sh -c "npx prisma migrate deploy && node dist/server.js"

  db:
    image: postgres:15
    restart: unless-stopped
    container_name: pedidofacildb
    env_file: .env.local
    networks:
      - pedidofacil_default
    ports:
      - '5432:5432'
    expose:
      - '5432'
    volumes:
      - pedidofacil_pgdata:/var/lib/postgresql/data

networks:
  pedidofacil_default:
    external: true

volumes:
  pedidofacil_pgdata:
