version: '3.8'

services:
  backend:
    container_name: pedidofacilapi
    build:
      context: .
      dockerfile: Dockerfile
      target: production
    ports:
      - '3333:3333'
    networks:
      - pedidofacilapi_default
    restart: unless-stopped
    env_file: .env.local
    depends_on:
      - db
    command: >
      sh -c "npx prisma migrate deploy && node dist/server.js"

  db:
    image: postgres:15
    restart: always
    container_name: pedidofacildb
    env_file: .env.local
    networks:
      - pedidofacilapi_default
    ports:
      - '5432:5432'
    expose:
      - '5432'

networks:
  pedidofacilapi_default:
